# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - spring-boot-greet-azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: set appsettings
        run: az webapp config appsettings set -g "akkitestRG1" -n "akkipayaljavy" --settings 'DBHOST=$DB_SERVER_NAME' 'DBNAME=fruits' 'DBUSER=demoadmin' 'DBPASS=88e3-1cf40c6144fd' 'PORT=8080' 'WEBSITES_PORT=8080' 
      - name: deploy app
        run: az webapp deploy --resource-group "akkitestRG1" --name "akkipayaljavy" --src-path ./*.jar --type jar
      
