name: ContosoUniversity-Infra

on:
  push:
    branches:
      - main

      
  # We also want to be able to run this manually from Github
  workflow_dispatch:
  

jobs:
  infra:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: Azure/login@v1.4.7
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Template
      run: |
           az group create --name "akkitestRG1" --location "uksouth"
           az appservice plan create --name "akkitestplan" --resource-group "akkitestRG1" --sku B2 --is-linux
           az webapp create --name "akkipayaljavy" --resource-group "akkitestRG1"  --runtime "JAVA|11-java11" --plan "akkitestplan"
           az postgres server create --resource-group "akkitestRG1" --name "akkiquarkuspostgres" --location "uksouth" --admin-user "demoadmin" --admin-password "88e3-1cf40c6144fd" --sku-name GP_Gen5_2
           az postgres server firewall-rule create --resource-group "akkitestRG1" --server-name "akkiquarkuspostgres" --name AllowMyIP --start-ip-address "49.36.176.252" --end-ip-address "49.36.176.252"
           az postgres server firewall-rule create --resource-group "akkitestRG1" --server-name "akkiquarkuspostgres" --name AllowAllWindowsAzureIps --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
           az postgres db create --resource-group "akkitestRG1" --server-name "akkiquarkuspostgres" --name fruits